version: "3.3"
services:
  wemap:
    container_name: wemap
    restart: always
    build: .
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: wemap-mongo
    image: "mongo:latest"
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
  redis:
    container_name: wemap-redis
    image: "redis:latest"
    restart: always
    ports:
      - 6379:6379
volumes:
  mongo-data: {}
